"""empty message

Revision ID: 7e0bbf1963bc
Revises: dd92c60c2884
Create Date: 2023-08-03 09:43:30.150960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0bbf1963bc'
down_revision = 'dd92c60c2884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_name', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.drop_column('plant_name')

    # ### end Alembic commands ###
