"""empty message

Revision ID: d273fe0f89e8
Revises: 99f9acbb4801
Create Date: 2023-08-08 13:47:52.761988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd273fe0f89e8'
down_revision = '99f9acbb4801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_user_plants_plant_id_plants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_plants_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_plant')
    with op.batch_alter_table('care_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_plant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_care_tasks_user_plant_id_user_plants'), 'user_plants', ['user_plant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_care_tasks_user_plant_id_user_plants'), type_='foreignkey')
        batch_op.drop_column('user_plant_id')

    op.create_table('user_plant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plant_id', sa.INTEGER(), nullable=False),
    sa.Column('care_task_id', sa.INTEGER(), nullable=True),
    sa.Column('plant_name', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['care_task_id'], ['care_tasks.id'], name='fk_user_plant_care_task_id_care_tasks'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name='fk_user_plant_plant_id_plants'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_plant_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_plants')
    # ### end Alembic commands ###
