"""empty message

Revision ID: dd92c60c2884
Revises: 
Create Date: 2023-08-02 21:15:05.018925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd92c60c2884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.alter_column('care_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.alter_column('care_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
